export { default as HomePage } from './HomePage'
export { default as CryptocurrenciesPage } from './CryptocurrenciesPage'
export { default as ExchangesPage } from './ExchangesPage'
export { default as NewsPage } from './NewsPage'
export { default as CryptoDetailPage } from './CryptoDetailPage'